name: Pull request automation

on:
  - pull_request

jobs:
  terraform_fmt:
    runs-on: ubuntu-latest
    name: terraform_fmt
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check if terraform files are formatted correctly.
        uses: dflook/terraform-fmt@v1

  terraform_docs:
    runs-on: ubuntu-latest
    name: terraform_docs
    needs: terraform_fmt
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and see if it's updated.
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "false"
