name: Pull request automation

on:
  - pull_request

jobs:
  Pull_request_automation:
    runs-on: ubuntu-latest
    name: Check if terraform files are formatted correctly.
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Terraform fmt
        uses: dflook/terraform-fmt@v1

      - name: Render terraform docs and see if it's updated.
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "false"
